git:
  depth: 999999
language: 
    - node_js
node_js:
    - "8"
cache:
  directories:
    - "node_modules"
install:
    - npm install
script: 
    - npm run build
deploy:
  provider: azure_web_apps
  verbose: true